### PR TITLE
some changes in code and alignment

### PR DESCRIPTION
**Pull request by Manthan5224**
hello, i've changed your code in main content part. i've simply used heading tag instead of using span in your paragraph tag.
and also i've done some alignment changes in your code, so it will be helpful for you when you want to update your site and will be easy to understand for another user.
hope this changes will be helpful for you.

### CODE REVIEW

**Comment by Castella1313** [comment]
@Manthan5224 setting up the alignment is a good idea, but I don't think its significant change. If you are interested to work on this repository, I can create issues(like the enhancements I want in my website)!!

**Comment by Manthan5224** [comment]
> @Manthan5224 setting up the alignment is a good idea, but I don't think its significant change. If you are interested to work on this repository, I can create issues(like the enhancements I want in my website)!!

Hey, Yeah sure you can create issue... I will try to solve your issues and will make something changes you want to do on your site

**Comment by Castella1313** [comment]
@Manthan5224  I have update the website, you can pull it again now and start solving the issues

**Comment by Manthan5224** [comment]
@Castella1313 Okay, I'll try to solve the issues, and if you don't mind may i redesign your website??? 
Cause i got some ideas for your website.

**Pull request closed without merging**
