### PR TITLE
Score UI added

### PR DESCRIPTION
**Pull request by dennis-pg**
Addressing [Issue](https://github.com/Castella1313/PYCHAMP/issues/2)

Instead of creating a new score page, added as a modal, since a new page would require passing the score as a parameter which will be visible in the URL.

### CODE REVIEW

**Comment by Castella1313** [comment]
@dennis-pg can you please tell me, is your pr being getting counted for Hacktoberfest??

**Comment by dennis-pg** [comment]
It didn't. Says the following:

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Review by Castella1313 — APPROVED** [review]

**Comment by Castella1313** [comment]
can you please tell me, is this pr still not getting counted.

**Comment by dennis-pg** [comment]
@Castella1313  Oddly, still no. Could you try adding the "hacktoberfest-accepted" tag to the PR?

**Comment by Castella1313** [comment]
do let me know, if its working

**Pull request merged**
