### PR TITLE
feat:Added text animation-typewriter to the title. It can solve ISSUE #4

### PR DESCRIPTION
**Pull request by symtalha14**
I have successfully added text animation to the title "QUIZ" in quiz.html file. I have made some changes in the project.css file also.

### CODE REVIEW

**Review by Castella1313 — APPROVED** [review]

**Comment by Castella1313** [comment]
resolve the conflicts

**Comment by Castella1313** [comment]
do let me know, if this pr of yours is being getting counted for Hacktoberfest or not!!

**Comment by symtalha14** [comment]
Kindly Check now

**Comment by symtalha14** [comment]
> do let me know, if this pr of yours is being getting counted for Hacktoberfest or not!!

Yes now it's counting in 👍

**Comment by symtalha14** [comment]
Hey,
Please consider merging if everything's in place :)

**Comment by symtalha14** [comment]
Helllo,
Can you please add the label "hacktoberfest-accepted" to this pull request. It's showing a status of "Not Approved" in the Hacktoberfest profile.

**Comment by Castella1313** [comment]
do let me know if its working

**Comment by symtalha14** [comment]
Yes It works. Really appreciate your kindness.

**Pull request merged**
